#!/bin/bash

# defaults
fit_type=""
input=""
output=""

# parse command line
function PrintUsage()
{
	echo "PrintUsage $0 <option> <option>"
	echo "OPTIONS:"
	echo "    -type <string>        fit type"
	echo "    -input <string>       input specification"
	echo "    -output <string>      output specification"
}

while [ -n "$1" ]
do
	case $1 in
		"-h" | "-help" | "--help")
			PrintUsage
			exit 0
			;;
		"-type")
			shift
			fit_type="$1"
			;;
		"-input")
			shift
			input="$1"
			;;
		"-output")
			shift
			output="$1"
			;;
		*)
			echo "ERROR: parameter '$1' not understood."
			PrintUsage
			exit 1
			;;
	esac

	shift
done

# validate input
if [ -z "$fit_type" -o -z "$input" -o -z "$output" ]
then
	echo "ERROR: insufficient input"
	PrintUsage
	exit 1
fi

# run the fit
if [ "$fit_type" == "HighBeta-single-0.015" ]
then
	$BASE_DIR/.make_fit -input-file "$input" -input-datasets "high_beta" \
		-output-root "fit_$output.root" -output-results "fit_$output.results" \
		-t-max-high-beta 0.015 \
			&> "fit_$output.log" || exit 10
	exit 0
fi

if [ "$fit_type" == "HighBeta-single-0.020" ]
then
	$BASE_DIR/.make_fit -input-file "$input" -input-datasets "high_beta" \
		-output-root "fit_$output.root" -output-results "fit_$output.results" \
		-t-max-high-beta 0.020 \
			&> "fit_$output.log" || exit 10
	exit 0
fi

if [ "$fit_type" == "HighBeta-3-single-0.020" ]
then
	$BASE_DIR/.make_fit -input-file "$input" -input-datasets "high_beta" \
		-output-root "fit_$output.root" -output-results "fit_$output.results" \
		-n-b 3 -t-max-high-beta 0.020 \
			&> "fit_$output.log" || exit 10
	exit 0
fi

if [ "$fit_type" == "HighBeta-sequence-0.005-0.020" ]
then
	tag="fit_${output}_step_a"
	$BASE_DIR/.make_fit -input-file "$input" -input-datasets "high_beta" -output-root "$tag.root" -output-results "$tag.results" \
		-init-eta 1. -use-eta-fixed 1\
		-init-rho 0.010 -use-rho-fixed 1\
		-t-min-high-beta 0.005 -t-max-high-beta 0.020 \
			&> "$tag.log" || exit 10

	Ap=`cat $tag.log|grep "Ap-->"`
	Ap=${Ap#*-->}

	b1=`cat $tag.log|grep "b1-->"`
	b1=${b1#*-->}

	tag="fit_${output}_step_b"
	$BASE_DIR/.make_fit -input-file "$input" -input-datasets "high_beta" -output-root "$tag.root" -output-results "$tag.results" \
		-use-A-from-Ap 1 -init-Ap "$Ap"\
		-init-rho 0.010 -use-rho-fixed 1\
		-init-b1 "$b1" -use-b1-fixed 1\
		-t-max-high-beta 0.0004 \
			&> "$tag.log" || exit 11

	eta=`cat $tag.log|grep "eta-->"`
	eta=${eta#*-->}

	A=`cat $tag.log|grep "A-->"`
	A=${A#*-->}

	tag="fit_${output}_step_c"
	$BASE_DIR/.make_fit -input-file "$input" -input-datasets "high_beta" -output-root "$tag.root" -output-results "$tag.results" \
		-init-eta "$eta" -use-eta-fixed 1\
		-init-A "$A" -use-A-fixed 1\
		-init-b1 "$b1" -use-b1-fixed 1\
		-t-max-high-beta 0.005 \
			&> "$tag.log" || exit 11

	exit 0
fi

if [ "$fit_type" == "BothBetas-single" ]
then
	$BASE_DIR/.make_fit -input-file "$input" -input-datasets "high_beta,low_beta" \
		-output-root "fit_$output.root" -output-results "fit_$output.results" &> "fit_$output.log" || exit 10
	exit 0
fi

# unknown fit type
echo "ERROR: unknown fit type '$fit_type'"
exit 2
