#!/bin/bash

# defaults
version=""
n_repetitions="5"
models="exp1_con_rho0.05 exp1_con_rho0.10 exp1_con_rho0.15"

input_version="version_TEST"

binnings="sb1,sb2,sb3"

# parse command line
function PrintUsage()
{
	echo "PrintUsage $0 <option> <option>"
	echo "OPTIONS:"
	echo "    -version <string>        version of the simulation"
	echo "    -repetitions <integer>   number of repetitions to use"
	echo "    -models <string>         space-separated list of models"
	echo "    -input-version <string>  version of the input"
	echo "    -binnings <string>       comma-separated list of binnings"
}

while [ -n "$1" ]
do
	case $1 in
		"-version")
			shift
			version="$1"
			;;
		"-repetitions")
			shift
			n_repetitions="$1"
			;;
		"-models")
			shift
			models="$1"
			;;
		"-input-version")
			shift
			input_version="$1"
			;;
		"-binnings")
			shift
			binnings="$1"
			;;
		*)
			echo "ERROR: parameter '$1' not understood."
			PrintUsage
			exit 1
			;;
	esac

	shift
done

# check input
if [ -z "$version" ]
then
	echo "ERROR: version not defined."
	PrintUsage
	exit 2
fi

# execute
make -j8 || exit 3

topDir="data/simu/$version"

mkdir -p "$topDir"
cd "$topDir"

$BASE_DIR/.simu_sample_models &> "models.log" || exit 21

for model in $models
do
	echo "* $model"

	mkdir -p "$model"
	cd "$model"

	for seed in `seq 1 $n_repetitions`
	do
		echo "  - $seed"

		mkdir -p "seed_$seed"
		cd "seed_$seed"

		$BASE_DIR/.simu_make_histograms -model-file "../../models.root" -model-obj "$model/g_dsdt_CH" \
			-input-file "$BASE_DIR/data/input/$input_version/import.root" -binnings "$binnings" -seed $seed \
			-sim-stat-err 1 -sim-syst-err 1 -sim-norm-err 1\
			&> "histograms.log" || exit 22

		$BASE_DIR/.make_fit &> "fit.log" || exit 23

		cd ..
	done

	$BASE_DIR/.simu_process_histograms -seed-min 1 -seed-max $n_repetitions -binnings "$binnings" &> "process_histograms.log" || exit 24

	$BASE_DIR/.simu_process_fits -seed-min 1 -seed-max $n_repetitions &> "process_fits.log" || exit 25

	cd ..
done
