#!/bin/bash

# defaults
version=""
n_repetitions="2"
models="con_rho0.05 con_rho0.10 con_rho0.15"

# parse command line
function PrintUsage()
{
	echo "PrintUsage $0 <option> <option>"
	echo "OPTIONS:"
	echo "    -version <string>        set version tag"
	echo "    -repetitions <integer>   number of repetitions to use"
	echo "    -models <string>         space-separated list of models"
}

while [ -n "$1" ]
do
	case $1 in
		"-version")
			shift
			version="$1"
			;;
		"-repetitions")
			shift
			n_repetitions="$1"
			;;
		"-models")
			shift
			models="$1"
			;;
		*)
			echo "ERROR: parameter '$1' not understood."
			PrintUsage
			exit 1
			;;
	esac

	shift
done

# check input
if [ -z "$version" ]
then
	echo "ERROR: version not defined."
	PrintUsage
	exit 2
fi

# execute
make -j8 || exit 3

topDir="data/simu/$version"

mkdir -p "$topDir"
cd "$topDir"

$BASE_DIR/.simu_sample_models &> "models.log" || exit 21

for model in $models
do
	mkdir -p "$model"
	cd "$model"

	for seed in `seq 1 $n_repetitions`
	do
		mkdir -p "seed_$seed"
		cd "seed_$seed"

		$BASE_DIR/.simu_make_histograms &> "histograms.log" || exit 22

		$BASE_DIR/.make_fit &> "fit.log" || exit 23

		cd ..
	done

	$BASE_DIR/.simu_process_histograms -seed-min 1 -seed-max $n_repetitions &> "process_histograms.log" || exit 24

	$BASE_DIR/.simu_process_fits -seed-min 1 -seed-max $n_repetitions &> "process_fits.log" || exit 25

	cd ..
done
